### ISSUE TITLE
is this working for 2.2.X

### ISSUE THREAD

**Issue by secaliskan** [menacoders/SortByDate#1]
Hi Mohammed, is your sorting module working on 2.2.X or 2.3.X??
Please advise.
regards

**Comment by secaliskan** [comment]
Hi I installed your module on 2.2.7 PHP 7.0 with centos 6 apache 2.4 +nginx engintron.
works like charm. Thank you, free seamless working module, without any customisation at backend. Only works on frontend catalog view and sorting the products by date from new to old!
This was what I need, Thank you

**Comment by growsera** [comment]
> Hi I installed your module on 2.2.7 PHP 7.0 with centos 6 apache 2.4 +nginx engintron.
> works like charm. Thank you, free seamless working module, without any customisation at backend. Only works on frontend catalog view and sorting the products by date from new to old!
> This was what I need, Thank you

great to hear that.

you are very welcome
